/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    roles: Role;
    media: Media;
    'home-activities': HomeActivity;
    faqs: Faq;
    'academy-articles': AcademyArticle;
    instruments: Instrument;
    'account-tiers': AccountTier;
    'account-benefits': AccountBenefit;
    'account-spreads': AccountSpread;
    'account-platforms': AccountPlatform;
    'trading-platforms': TradingPlatform;
    'funding-methods': FundingMethod;
    testimonials: Testimonial;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    roles: RolesSelect<false> | RolesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'home-activities': HomeActivitiesSelect<false> | HomeActivitiesSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    'academy-articles': AcademyArticlesSelect<false> | AcademyArticlesSelect<true>;
    instruments: InstrumentsSelect<false> | InstrumentsSelect<true>;
    'account-tiers': AccountTiersSelect<false> | AccountTiersSelect<true>;
    'account-benefits': AccountBenefitsSelect<false> | AccountBenefitsSelect<true>;
    'account-spreads': AccountSpreadsSelect<false> | AccountSpreadsSelect<true>;
    'account-platforms': AccountPlatformsSelect<false> | AccountPlatformsSelect<true>;
    'trading-platforms': TradingPlatformsSelect<false> | TradingPlatformsSelect<true>;
    'funding-methods': FundingMethodsSelect<false> | FundingMethodsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale:
    ('false' | 'none' | 'null') | false | null | ('zh-Hant' | 'zh-Hans' | 'en') | ('zh-Hant' | 'zh-Hans' | 'en')[];
  globals: {
    'site-settings': SiteSetting;
    'home-page': HomePage;
    'trading-page': TradingPage;
    'about-page': AboutPage;
    'products-page': ProductsPage;
    'funding-page': FundingPage;
    'platforms-page': PlatformsPage;
    'sample-trading-conditions': SampleTradingCondition;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'trading-page': TradingPageSelect<false> | TradingPageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'products-page': ProductsPageSelect<false> | ProductsPageSelect<true>;
    'funding-page': FundingPageSelect<false> | FundingPageSelect<true>;
    'platforms-page': PlatformsPageSelect<false> | PlatformsPageSelect<true>;
    'sample-trading-conditions': SampleTradingConditionsSelect<false> | SampleTradingConditionsSelect<true>;
  };
  locale: 'zh-Hant' | 'zh-Hans' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * CMS login accounts. Each user is assigned a Role that decides their permissions.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * The role assigned to this account. Manage roles under System → Roles.
   */
  role?: (number | null) | Role;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * CMS roles & permissions. Full access = administrator (all permissions). Otherwise tick per-resource / per-field permissions.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles".
 */
export interface Role {
  id: number;
  name: string;
  /**
   * Grants every permission and can manage roles & users. Ignores the matrix below.
   */
  fullAccess?: boolean | null;
  can__home_activities__create?: boolean | null;
  can__home_activities__update?: boolean | null;
  can__home_activities__delete?: boolean | null;
  /**
   * Also requires this resource’s Update permission.
   */
  fld__home_activities__enabled__update?: boolean | null;
  can__faqs__create?: boolean | null;
  can__faqs__update?: boolean | null;
  can__faqs__delete?: boolean | null;
  /**
   * Also requires this resource’s Update permission.
   */
  fld__faqs__enabled__update?: boolean | null;
  can__academy_articles__create?: boolean | null;
  can__academy_articles__update?: boolean | null;
  can__academy_articles__delete?: boolean | null;
  /**
   * Also requires this resource’s Update permission.
   */
  fld__academy_articles__slug__update?: boolean | null;
  /**
   * Also requires this resource’s Update permission.
   */
  fld__academy_articles__enabled__update?: boolean | null;
  can__instruments__create?: boolean | null;
  can__instruments__update?: boolean | null;
  can__instruments__delete?: boolean | null;
  /**
   * Also requires this resource’s Update permission.
   */
  fld__instruments__enabled__update?: boolean | null;
  can__account_tiers__create?: boolean | null;
  can__account_tiers__update?: boolean | null;
  can__account_tiers__delete?: boolean | null;
  /**
   * Also requires this resource’s Update permission.
   */
  fld__account_tiers__enabled__update?: boolean | null;
  can__account_benefits__create?: boolean | null;
  can__account_benefits__update?: boolean | null;
  can__account_benefits__delete?: boolean | null;
  /**
   * Also requires this resource’s Update permission.
   */
  fld__account_benefits__enabled__update?: boolean | null;
  can__account_spreads__create?: boolean | null;
  can__account_spreads__update?: boolean | null;
  can__account_spreads__delete?: boolean | null;
  /**
   * Also requires this resource’s Update permission.
   */
  fld__account_spreads__enabled__update?: boolean | null;
  can__account_platforms__create?: boolean | null;
  can__account_platforms__update?: boolean | null;
  can__account_platforms__delete?: boolean | null;
  /**
   * Also requires this resource’s Update permission.
   */
  fld__account_platforms__enabled__update?: boolean | null;
  can__trading_platforms__create?: boolean | null;
  can__trading_platforms__update?: boolean | null;
  can__trading_platforms__delete?: boolean | null;
  /**
   * Also requires this resource’s Update permission.
   */
  fld__trading_platforms__enabled__update?: boolean | null;
  can__funding_methods__create?: boolean | null;
  can__funding_methods__update?: boolean | null;
  can__funding_methods__delete?: boolean | null;
  /**
   * Also requires this resource’s Update permission.
   */
  fld__funding_methods__enabled__update?: boolean | null;
  can__testimonials__create?: boolean | null;
  can__testimonials__update?: boolean | null;
  can__testimonials__delete?: boolean | null;
  /**
   * Also requires this resource’s Update permission.
   */
  fld__testimonials__enabled__update?: boolean | null;
  can__media__create?: boolean | null;
  can__media__update?: boolean | null;
  can__media__delete?: boolean | null;
  can__users__read?: boolean | null;
  can__users__create?: boolean | null;
  can__users__update?: boolean | null;
  can__users__delete?: boolean | null;
  /**
   * Also requires this resource’s Update permission.
   */
  fld__users__role__update?: boolean | null;
  can__site_settings__update?: boolean | null;
  can__home_page__update?: boolean | null;
  can__trading_page__update?: boolean | null;
  can__about_page__update?: boolean | null;
  can__products_page__update?: boolean | null;
  can__funding_page__update?: boolean | null;
  can__platforms_page__update?: boolean | null;
  can__sample_trading_conditions__update?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Uploaded images and files used across the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Homepage news & activities cards. Create / edit / sort / publish; 3 locales.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-activities".
 */
export interface HomeActivity {
  id: number;
  title: string;
  summary?: string | null;
  /**
   * e.g. Event, Notice, Product, Platform.
   */
  tag?: string | null;
  /**
   * If empty, the front-end shows a brand gradient banner.
   */
  image?: (number | null) | Media;
  /**
   * Optional; when set, the card is clickable.
   */
  href?: string | null;
  date?: string | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  enabled?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * FAQs by category. Front-end falls back to i18n seeds when empty / no DB.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: string;
  category: 'trading' | 'products' | 'accounts' | 'platforms' | 'general';
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  enabled?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Gold Academy articles. Neutral education only — not investment advice. Falls back to i18n seeds without DB.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "academy-articles".
 */
export interface AcademyArticle {
  id: number;
  title: string;
  /**
   * Used for /academy/[slug]; unique site-wide; prefer ASCII + hyphens.
   */
  slug: string;
  /**
   * Short blurb for list / homepage cards.
   */
  excerpt?: string | null;
  /**
   * Full article (Lexical). Neutral education — not investment advice.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * If empty, the front-end uses a brand gradient or seed placeholder.
   */
  cover?: (number | null) | Media;
  /**
   * e.g. Basics, MT5 practice, Macro view.
   */
  category?: string | null;
  publishedAt?: string | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  enabled?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * ⚠️ SAMPLE product table for /products/all. Contract size / spread / leverage / hours are illustrative (front-end keeps the sample label), NOT approved facts. Approved figures live in tradingConditions.ts. Empty / no DB = i18n seed fallback.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "instruments".
 */
export interface Instrument {
  id: number;
  name: string;
  symbol: string;
  /**
   * Rows are grouped by category on the page.
   */
  category: 'metals' | 'forex' | 'indices' | 'energy' | 'other';
  contractSize?: string | null;
  spread?: string | null;
  leverage?: string | null;
  tradingHours?: string | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  enabled?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * ⚠️ SAMPLE account cards for /accounts. Min deposit / spread / commission / leverage / execution / platform are illustrative (front-end keeps the sample label), NOT approved facts. Approved figures live in tradingConditions.ts. Empty / no DB = i18n seed fallback.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "account-tiers".
 */
export interface AccountTier {
  id: number;
  name: string;
  code: string;
  badge?: string | null;
  /**
   * Highlighted with a gold border. Use on at most one tier.
   */
  popular?: boolean | null;
  desc?: string | null;
  minDeposit?: string | null;
  spread?: string | null;
  commission?: string | null;
  leverage?: string | null;
  execution?: string | null;
  platform?: string | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  enabled?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Core benefit cards for /accounts. Empty / no DB = i18n seed fallback.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "account-benefits".
 */
export interface AccountBenefit {
  id: number;
  title: string;
  desc?: string | null;
  icon: 'percent' | 'zap' | 'creditCard' | 'monitor';
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  enabled?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * ⚠️ SAMPLE spreads preview for /accounts. Bid / ask / spread are illustrative (front-end keeps the sample label), NOT a live feed or approved fact. Approved average spreads live in tradingConditions.ts. Empty / no DB = i18n seed fallback.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "account-spreads".
 */
export interface AccountSpread {
  id: number;
  pair: string;
  bid?: string | null;
  ask?: string | null;
  spread?: string | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  enabled?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Supported-platform cards for /accounts. Empty / no DB = i18n seed fallback.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "account-platforms".
 */
export interface AccountPlatform {
  id: number;
  name: string;
  desc?: string | null;
  /**
   * Short label drawn on the placeholder panel (not localised).
   */
  panelLabel?: string | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  enabled?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Platform tabs for /platforms. Empty / no DB = i18n seed fallback.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trading-platforms".
 */
export interface TradingPlatform {
  id: number;
  name: string;
  /**
   * Short label drawn on the placeholder panel (not localised).
   */
  panelLabel?: string | null;
  tagline?: string | null;
  desc?: string | null;
  /**
   * Real platform/device screenshot. Empty = Figma sample mockup (labelled 示意).
   */
  visual?: (number | null) | Media;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  enabled?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * ⚠️ SAMPLE deposit/withdrawal channels for /funding. Use "Type" to route each row to the deposit or withdrawal table. Method / time / fee / currencies are illustrative (front-end keeps the sample label), NOT approved facts or guarantees. Empty / no DB = i18n seed fallback.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "funding-methods".
 */
export interface FundingMethod {
  id: number;
  /**
   * Deposit rows show in the 入金 table; withdrawal rows in the 出金 table.
   */
  type: 'deposit' | 'withdrawal';
  method: string;
  time?: string | null;
  fee?: string | null;
  free?: boolean | null;
  currencies?: string | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  enabled?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Real, review-approved client testimonials. Do NOT invent quotes or people. Empty = the front-end testimonials section is hidden.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  quote: string;
  authorName: string;
  authorTitle?: string | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  enabled?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'roles';
        value: number | Role;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'home-activities';
        value: number | HomeActivity;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'academy-articles';
        value: number | AcademyArticle;
      } | null)
    | ({
        relationTo: 'instruments';
        value: number | Instrument;
      } | null)
    | ({
        relationTo: 'account-tiers';
        value: number | AccountTier;
      } | null)
    | ({
        relationTo: 'account-benefits';
        value: number | AccountBenefit;
      } | null)
    | ({
        relationTo: 'account-spreads';
        value: number | AccountSpread;
      } | null)
    | ({
        relationTo: 'account-platforms';
        value: number | AccountPlatform;
      } | null)
    | ({
        relationTo: 'trading-platforms';
        value: number | TradingPlatform;
      } | null)
    | ({
        relationTo: 'funding-methods';
        value: number | FundingMethod;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles_select".
 */
export interface RolesSelect<T extends boolean = true> {
  name?: T;
  fullAccess?: T;
  can__home_activities__create?: T;
  can__home_activities__update?: T;
  can__home_activities__delete?: T;
  fld__home_activities__enabled__update?: T;
  can__faqs__create?: T;
  can__faqs__update?: T;
  can__faqs__delete?: T;
  fld__faqs__enabled__update?: T;
  can__academy_articles__create?: T;
  can__academy_articles__update?: T;
  can__academy_articles__delete?: T;
  fld__academy_articles__slug__update?: T;
  fld__academy_articles__enabled__update?: T;
  can__instruments__create?: T;
  can__instruments__update?: T;
  can__instruments__delete?: T;
  fld__instruments__enabled__update?: T;
  can__account_tiers__create?: T;
  can__account_tiers__update?: T;
  can__account_tiers__delete?: T;
  fld__account_tiers__enabled__update?: T;
  can__account_benefits__create?: T;
  can__account_benefits__update?: T;
  can__account_benefits__delete?: T;
  fld__account_benefits__enabled__update?: T;
  can__account_spreads__create?: T;
  can__account_spreads__update?: T;
  can__account_spreads__delete?: T;
  fld__account_spreads__enabled__update?: T;
  can__account_platforms__create?: T;
  can__account_platforms__update?: T;
  can__account_platforms__delete?: T;
  fld__account_platforms__enabled__update?: T;
  can__trading_platforms__create?: T;
  can__trading_platforms__update?: T;
  can__trading_platforms__delete?: T;
  fld__trading_platforms__enabled__update?: T;
  can__funding_methods__create?: T;
  can__funding_methods__update?: T;
  can__funding_methods__delete?: T;
  fld__funding_methods__enabled__update?: T;
  can__testimonials__create?: T;
  can__testimonials__update?: T;
  can__testimonials__delete?: T;
  fld__testimonials__enabled__update?: T;
  can__media__create?: T;
  can__media__update?: T;
  can__media__delete?: T;
  can__users__read?: T;
  can__users__create?: T;
  can__users__update?: T;
  can__users__delete?: T;
  fld__users__role__update?: T;
  can__site_settings__update?: T;
  can__home_page__update?: T;
  can__trading_page__update?: T;
  can__about_page__update?: T;
  can__products_page__update?: T;
  can__funding_page__update?: T;
  can__platforms_page__update?: T;
  can__sample_trading_conditions__update?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-activities_select".
 */
export interface HomeActivitiesSelect<T extends boolean = true> {
  title?: T;
  summary?: T;
  tag?: T;
  image?: T;
  href?: T;
  date?: T;
  order?: T;
  enabled?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  order?: T;
  enabled?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "academy-articles_select".
 */
export interface AcademyArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  body?: T;
  cover?: T;
  category?: T;
  publishedAt?: T;
  order?: T;
  enabled?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "instruments_select".
 */
export interface InstrumentsSelect<T extends boolean = true> {
  name?: T;
  symbol?: T;
  category?: T;
  contractSize?: T;
  spread?: T;
  leverage?: T;
  tradingHours?: T;
  order?: T;
  enabled?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "account-tiers_select".
 */
export interface AccountTiersSelect<T extends boolean = true> {
  name?: T;
  code?: T;
  badge?: T;
  popular?: T;
  desc?: T;
  minDeposit?: T;
  spread?: T;
  commission?: T;
  leverage?: T;
  execution?: T;
  platform?: T;
  order?: T;
  enabled?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "account-benefits_select".
 */
export interface AccountBenefitsSelect<T extends boolean = true> {
  title?: T;
  desc?: T;
  icon?: T;
  order?: T;
  enabled?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "account-spreads_select".
 */
export interface AccountSpreadsSelect<T extends boolean = true> {
  pair?: T;
  bid?: T;
  ask?: T;
  spread?: T;
  order?: T;
  enabled?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "account-platforms_select".
 */
export interface AccountPlatformsSelect<T extends boolean = true> {
  name?: T;
  desc?: T;
  panelLabel?: T;
  order?: T;
  enabled?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trading-platforms_select".
 */
export interface TradingPlatformsSelect<T extends boolean = true> {
  name?: T;
  panelLabel?: T;
  tagline?: T;
  desc?: T;
  visual?: T;
  order?: T;
  enabled?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "funding-methods_select".
 */
export interface FundingMethodsSelect<T extends boolean = true> {
  type?: T;
  method?: T;
  time?: T;
  fee?: T;
  free?: T;
  currencies?: T;
  order?: T;
  enabled?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  authorName?: T;
  authorTitle?: T;
  order?: T;
  enabled?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Customer-service / contact operational links.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  whatsapp?: string | null;
  phone?: string | null;
  email?: string | null;
  liveChatUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Homepage marketing overrides (hero / section intros / CTAs). Layout stays in code; empty = i18n default.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  heroBadge?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  heroTitleLine1?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  heroTitleBrand?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  heroTitleTail?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  heroSubtitle?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  heroCtaPrimary?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  servicesKicker?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  servicesHeading?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  servicesSubheading?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  servicesBody?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  servicesCta?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  mt5Kicker?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  mt5Heading?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  mt5Subheading?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  mt5Body?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  mt5CtaPrimary?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  mt5CtaSecondary?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  whyKicker?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  whyHeading?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  academyKicker?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  academyHeading?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  storyKicker?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  storyHeading?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  storyBody?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  storyCta?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  supportKicker?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  supportHeading?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  supportCta?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  finalHeading?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  finalBody?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  finalCtaPrimary?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  finalCtaSecondary?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Trading overview (/trading) marketing overrides. Edit sample tables under “Sample trading tables”. Empty = i18n default.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trading-page".
 */
export interface TradingPage {
  id: number;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  heroTitleLine1?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  heroTitleLine2?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  heroSubtitle?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  servicesBadge?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  servicesHeading?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  servicesSubtitle?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  accountsBadge?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  accountsHeading?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  accountsSubtitle?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  pricingBadge?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  pricingHeading?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  pricingSubtitle?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  pricingCta?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  faqBadge?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  faqHeading?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  faqSubtitle?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  ctaHeading?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  ctaBody?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * About-page marketing overrides. Credentials / milestone facts stay in code / FACTS. Empty = i18n default.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  heroTitleLead?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  heroSubtitle?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  identityKicker?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  identityHeading?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  credentialsKicker?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  credentialsHeading?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  principlesKicker?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  principlesHeading?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  timelineKicker?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  timelineHeading?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  hongkongKicker?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  hongkongHeadingLead?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  hongkongHeadingAccent?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  hongkongBody?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  galleryKicker?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  galleryHeading?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  ctaHeading?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  ctaBody?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  ctaSecondary?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Products-page marketing overrides. Approved spreads/leverage live in tradingConditions.ts — do not change numbers here. Empty = i18n default.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products-page".
 */
export interface ProductsPage {
  id: number;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  heroTitleLead?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  heroTitleAccent?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  heroTitleTail?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  heroSubtitle?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  listKicker?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  listHeading?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  listSubheading?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  conditionsKicker?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  conditionsHeading?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  credibilityKicker?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  credibilityHeading?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  ctaHeading?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  ctaBody?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Deposit/withdrawal page marketing copy. Channels are edited in "Funding methods"; testimonials in "Testimonials". Empty = i18n default.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "funding-page".
 */
export interface FundingPage {
  id: number;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  heroTitleLead?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  heroTitleAccent?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  heroTitleTail?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  heroSubtitle?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  depositIntroHeading?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  depositIntroBody?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  depositMethodsKicker?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  depositMethodsHeading?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  depositMethodsNote?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  withdrawIntroHeading?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  withdrawIntroBody?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  withdrawMethodsKicker?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  withdrawMethodsHeading?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  withdrawMethodsNote?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  topicsKicker?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  topicsHeading?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  topicsSubtitle?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  testimonialsKicker?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  testimonialsHeading?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  testimonialsSubtitle?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  ctaHeading?: string | null;
  /**
   * 留空＝使用網站預設文案（i18n）。
   */
  ctaBody?: string | null;
  /**
   * Optional. Empty = built-in placeholder image.
   */
  heroImage?: (number | null) | Media;
  /**
   * Optional. Empty = built-in placeholder image.
   */
  depositImage?: (number | null) | Media;
  /**
   * Optional. Empty = built-in placeholder image.
   */
  withdrawImage?: (number | null) | Media;
  /**
   * Optional. Empty = built-in placeholder image.
   */
  ctaImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Trading-platforms page hero image. Per-platform screenshots are edited in "Trading platforms". Empty = Figma sample mockup.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "platforms-page".
 */
export interface PlatformsPage {
  id: number;
  /**
   * Multi-device showcase shown in the hero. Empty = Figma sample mockup (labelled 示意).
   */
  heroImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * ⚠️ SAMPLE data only (not approved facts). Front-end keeps the sample label. Approved spreads/leverage live on /products (tradingConditions.ts). Empty arrays = sampleTradingData seeds.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sample-trading-conditions".
 */
export interface SampleTradingCondition {
  id: number;
  /**
   * bid／ask／spread／change 皆為示意數字，上線前由業主替換。
   */
  pricingRows?:
    | {
        symbol: string;
        nameKey: 'londonGold' | 'kilobarHkd';
        bid: string;
        ask: string;
        spread: string;
        change: string;
        id?: string | null;
      }[]
    | null;
  /**
   * 雙帳戶比較為示意格式。rowKey 對應 i18n trading.accounts.rows.*；type=text 時填 value（localized）。
   */
  accountRows?:
    | {
        /**
         * 必須對應 trading.accounts.rows.<key> 的 i18n 標籤鍵。
         */
        rowKey: string;
        standard: {
          type: 'pending' | 'text' | 'check' | 'priority' | 'dash';
          /**
           * 留空且 type=text 時，前台回退 i18n（若有對應鍵）。
           */
          value?: string | null;
          /**
           * 對應 trading.accounts.<textKey>；value 優先。
           */
          textKey?: string | null;
        };
        professional: {
          type: 'pending' | 'text' | 'check' | 'priority' | 'dash';
          value?: string | null;
          textKey?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  whatsapp?: T;
  phone?: T;
  email?: T;
  liveChatUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  heroBadge?: T;
  heroTitleLine1?: T;
  heroTitleBrand?: T;
  heroTitleTail?: T;
  heroSubtitle?: T;
  heroCtaPrimary?: T;
  servicesKicker?: T;
  servicesHeading?: T;
  servicesSubheading?: T;
  servicesBody?: T;
  servicesCta?: T;
  mt5Kicker?: T;
  mt5Heading?: T;
  mt5Subheading?: T;
  mt5Body?: T;
  mt5CtaPrimary?: T;
  mt5CtaSecondary?: T;
  whyKicker?: T;
  whyHeading?: T;
  academyKicker?: T;
  academyHeading?: T;
  storyKicker?: T;
  storyHeading?: T;
  storyBody?: T;
  storyCta?: T;
  supportKicker?: T;
  supportHeading?: T;
  supportCta?: T;
  finalHeading?: T;
  finalBody?: T;
  finalCtaPrimary?: T;
  finalCtaSecondary?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trading-page_select".
 */
export interface TradingPageSelect<T extends boolean = true> {
  heroTitleLine1?: T;
  heroTitleLine2?: T;
  heroSubtitle?: T;
  servicesBadge?: T;
  servicesHeading?: T;
  servicesSubtitle?: T;
  accountsBadge?: T;
  accountsHeading?: T;
  accountsSubtitle?: T;
  pricingBadge?: T;
  pricingHeading?: T;
  pricingSubtitle?: T;
  pricingCta?: T;
  faqBadge?: T;
  faqHeading?: T;
  faqSubtitle?: T;
  ctaHeading?: T;
  ctaBody?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  heroTitleLead?: T;
  heroSubtitle?: T;
  identityKicker?: T;
  identityHeading?: T;
  credentialsKicker?: T;
  credentialsHeading?: T;
  principlesKicker?: T;
  principlesHeading?: T;
  timelineKicker?: T;
  timelineHeading?: T;
  hongkongKicker?: T;
  hongkongHeadingLead?: T;
  hongkongHeadingAccent?: T;
  hongkongBody?: T;
  galleryKicker?: T;
  galleryHeading?: T;
  ctaHeading?: T;
  ctaBody?: T;
  ctaSecondary?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products-page_select".
 */
export interface ProductsPageSelect<T extends boolean = true> {
  heroTitleLead?: T;
  heroTitleAccent?: T;
  heroTitleTail?: T;
  heroSubtitle?: T;
  listKicker?: T;
  listHeading?: T;
  listSubheading?: T;
  conditionsKicker?: T;
  conditionsHeading?: T;
  credibilityKicker?: T;
  credibilityHeading?: T;
  ctaHeading?: T;
  ctaBody?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "funding-page_select".
 */
export interface FundingPageSelect<T extends boolean = true> {
  heroTitleLead?: T;
  heroTitleAccent?: T;
  heroTitleTail?: T;
  heroSubtitle?: T;
  depositIntroHeading?: T;
  depositIntroBody?: T;
  depositMethodsKicker?: T;
  depositMethodsHeading?: T;
  depositMethodsNote?: T;
  withdrawIntroHeading?: T;
  withdrawIntroBody?: T;
  withdrawMethodsKicker?: T;
  withdrawMethodsHeading?: T;
  withdrawMethodsNote?: T;
  topicsKicker?: T;
  topicsHeading?: T;
  topicsSubtitle?: T;
  testimonialsKicker?: T;
  testimonialsHeading?: T;
  testimonialsSubtitle?: T;
  ctaHeading?: T;
  ctaBody?: T;
  heroImage?: T;
  depositImage?: T;
  withdrawImage?: T;
  ctaImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "platforms-page_select".
 */
export interface PlatformsPageSelect<T extends boolean = true> {
  heroImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sample-trading-conditions_select".
 */
export interface SampleTradingConditionsSelect<T extends boolean = true> {
  pricingRows?:
    | T
    | {
        symbol?: T;
        nameKey?: T;
        bid?: T;
        ask?: T;
        spread?: T;
        change?: T;
        id?: T;
      };
  accountRows?:
    | T
    | {
        rowKey?: T;
        standard?:
          | T
          | {
              type?: T;
              value?: T;
              textKey?: T;
            };
        professional?:
          | T
          | {
              type?: T;
              value?: T;
              textKey?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}